---
- set_fact: var_interfaces_db='{{var_interfaces_db}}{{ item.interface }};{{ item.ip }}\n'
  with_items: "{{ openstack_external_interfaces }}"
  vars:
     - var_interfaces_db: ""

- debug: var=var_interfaces_db

- name: Copy network interface db
  shell: 'echo "{{ var_interfaces_db }}" > /home/centos/neutron_ovs_multiplex_interfaces_db'

- set_fact: var_interfaces='{{ var_interfaces }} {{ item.interface }}'
  with_items: "{{ openstack_external_interfaces }}"
  vars:
     - var_interfaces: ""

- name: 'Set bridge br-ex protocol to "{{ openvswitch_bridge_protocols }}'
  command: 'ovs-vsctl set bridge br-ex protocols={{ openvswitch_bridge_protocols }}'
  run_once: True

- name: 'Execute script for clean interfaces'
  command: '/home/centos/neutron-ovs-multiplex.sh clean'
  run_once: True

- name: 'Execute map script'
  command: '/home/centos/neutron-ovs-multiplex.sh map {{ var_interfaces }}'
  run_once: True
